{
  "formatVersion": "1.1",
  "component": {
    "group": "io.hasura",
    "module": "ndc-sdk-kotlin",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ndc-sdk-kotlin-1.0.9.jar",
          "url": "ndc-sdk-kotlin-1.0.9.jar",
          "size": 1315809,
          "sha512": "9b88825f12fc4211a43e984163a8b5a0ec563b1f10f73d299be804a0d9d004a103685ba234c86cbf805fd94b67ff42717b2bed9d24b70984e0047d6051ec9618",
          "sha256": "56acb9a6f6062a3bce9240250466ef5afdebd73aff62c167ec561097fe0d380f",
          "sha1": "4a1c38b95e2721a8726d23fb1c1efb1ce2b45883",
          "md5": "2f5001ada65843480a3e3e0e3b663c90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-cli",
          "version": {
            "requires": "0.3.6"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-lang-kotlin",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-lang-kotlin-coroutines",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-registry-prometheus",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.46.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.46.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-extension-kotlin",
          "version": {
            "requires": "1.46.0"
          }
        },
        {
          "group": "io.opentelemetry.semconv",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.30.0-rc.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.46.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ndc-sdk-kotlin-1.0.9.jar",
          "url": "ndc-sdk-kotlin-1.0.9.jar",
          "size": 1315809,
          "sha512": "9b88825f12fc4211a43e984163a8b5a0ec563b1f10f73d299be804a0d9d004a103685ba234c86cbf805fd94b67ff42717b2bed9d24b70984e0047d6051ec9618",
          "sha256": "56acb9a6f6062a3bce9240250466ef5afdebd73aff62c167ec561097fe0d380f",
          "sha1": "4a1c38b95e2721a8726d23fb1c1efb1ce2b45883",
          "md5": "2f5001ada65843480a3e3e0e3b663c90"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ndc-sdk-kotlin-1.0.9-all.jar",
          "url": "ndc-sdk-kotlin-1.0.9-all.jar",
          "size": 19097087,
          "sha512": "86bb042b23bb176bf61c58564ee5b1f8a8b6fbd935ac96e885be2cc06494ccc440bf2da062eb2e284585aa7886140366d345caf5d7117430be363c535021dc79",
          "sha256": "3dca0124d3f629dc860ad5d1a6778612a87773c564f7d4855f7f1cc10f2d4e6c",
          "sha1": "6001773e7bb5574ae5b5dd83c5339fc9c6c4170c",
          "md5": "a9ea7d0f8bf90e2b89419c13a1e1f558"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ndc-sdk-kotlin-1.0.9-sources.jar",
          "url": "ndc-sdk-kotlin-1.0.9-sources.jar",
          "size": 19225,
          "sha512": "6f14fbee433c2d3d317fd07e401404f2869183b1f100c177a4d2e35658ac5136554da56bca46d2faffbffa6f118628b693c5005b59beff309087a58cd4cf53ac",
          "sha256": "6e65589bc017312a28dbc49c23e6475c5f82090112e7b4f3f88ffd511a8c82d2",
          "sha1": "7295d303489f9c692e148669637e1748bf7cee5d",
          "md5": "b0857dda39e940e50bfa5891edc8a7ce"
        }
      ]
    }
  ]
}
