{
  "formatVersion": "1.1",
  "component": {
    "group": "io.hasura",
    "module": "ndc-sdk-kotlin",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ndc-sdk-kotlin-1.0.3.jar",
          "url": "ndc-sdk-kotlin-1.0.3.jar",
          "size": 551985,
          "sha512": "c6ce5e9b9361f5fc19be55f97295e8c21eb74f57a60d8b999785ff2dd3f92322eb221d408e29ff239445210ac993f1a943023078e45890dc9cd5d4c98b214d3b",
          "sha256": "140b1c87a7eacc0f5cf038ec4b6d6a5605a5ea4bcfee0b43eb201994acc2b569",
          "sha1": "9893b0e44181a0fcb60b464e3790b672ddff0c48",
          "md5": "5433f72adb34d5fd74135fd42ca0571f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-cli",
          "version": {
            "requires": "0.3.6"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-core",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-web",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-lang-kotlin",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "io.vertx",
          "module": "vertx-lang-kotlin-coroutines",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.15"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-registry-prometheus",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.46.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.46.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-extension-kotlin",
          "version": {
            "requires": "1.46.0"
          }
        },
        {
          "group": "io.opentelemetry.semconv",
          "module": "opentelemetry-semconv",
          "version": {
            "requires": "1.30.0-rc.1"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.46.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ndc-sdk-kotlin-1.0.3.jar",
          "url": "ndc-sdk-kotlin-1.0.3.jar",
          "size": 551985,
          "sha512": "c6ce5e9b9361f5fc19be55f97295e8c21eb74f57a60d8b999785ff2dd3f92322eb221d408e29ff239445210ac993f1a943023078e45890dc9cd5d4c98b214d3b",
          "sha256": "140b1c87a7eacc0f5cf038ec4b6d6a5605a5ea4bcfee0b43eb201994acc2b569",
          "sha1": "9893b0e44181a0fcb60b464e3790b672ddff0c48",
          "md5": "5433f72adb34d5fd74135fd42ca0571f"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ndc-sdk-kotlin-1.0.3-all.jar",
          "url": "ndc-sdk-kotlin-1.0.3-all.jar",
          "size": 18333263,
          "sha512": "fe1ecdb383d2099aed6e84af636937e591dbded91e09bcf0f28d4e402e879361db2bb731eb191d54907aeba8af96691fbca6b067051f97332305ac025ab8eba9",
          "sha256": "9eacfddf7aa86c348be68ef210edddf9974c1dc23d03bccf0d4d6f449e1473d0",
          "sha1": "0bafb4af72af81c4058319ae05cf305f007ab889",
          "md5": "49d3cb45305d1c681cfe9e7e97be9fa0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ndc-sdk-kotlin-1.0.3-sources.jar",
          "url": "ndc-sdk-kotlin-1.0.3-sources.jar",
          "size": 16613,
          "sha512": "3167d98ccb2622340f5b98143ab1329584526c9d69933b831adf6b22046745d68351378e581f3ecba5298358913691ca0a64aaf66bc67e69325f1751cfe0e5df",
          "sha256": "e0a1de01dd0cfb4a93c9591738639bd54ffb5331e35762ec9842911351e1bbcc",
          "sha1": "83d07f5d1c6408ab666cba53bf40464488f48285",
          "md5": "8250554411b7f5595ce52e472683bea3"
        }
      ]
    }
  ]
}
